InstructionMemory = (
    "WRITE RegisterA Welcome to the number guessing game!",
    "WRITE RegisterB You have only three tries to guess the secret number.",
    "WRITE RegisterC The number is a integer between 1 and 20.",
    "WRITE RegisterD Good luck and enjoy!",
    "WRITE RegisterE 14",
    "READ RegisterA",
    "READ RegisterB",
    "READ RegisterC",
    "READ RegisterD",
    "CollectINT Guess: ",
    "CompareR=E,I",
    "CollectINT Guess: ",
    "CompareR=E,I",
    "CollectINT Guess: ",
    "CompareR=E,I",
    )
