InstructionMemory = (
    "ADD 10,20",
    "SUB 15,10",
    "MUL 12,17",
    "DIV 16,24",
    "MOD 34,9",
    "FINAL SUM",
    "READ RegisterA",
    "WRITE RegisterA Perl",
    "READ RegisterA",
    "READ RegisterB",
    "WRITE RegisterB Python",
    "READ RegisterB",
    "READ RegisterC",
    "WRITE RegisterC MongoDB",
    "READ RegisterC",
    "READ RegisterD",
    "WRITE RegisterD Data Structures",
    "READ RegisterD",
    "CycleCount",
    "YES 1",
    "NOT 0",
    "AND 1,1",
    "OR 1,0",
    "XOR 1,1",
    "NAND 0,0",
    "NOR 1,0",
    "XNOR 0,1",
    "CollectINT Enter a numberL ",
    "CollectSTRING What is your favorite food? ",
    "CollectFLOAT What is your grade in math? ",
    "CollectBOOLEAN BroWSG Are you older than 10? (True/False) ",
    "READ InputRegister",
    "Compare= 5,5")
